version: '3.8'
services:
    dashcore:
        container_name: hs-dashcore
        command: /app/dashcore/bin/dashd -conf=/app/dashcore/conf/dash.conf -datadir=/data/dashcore
        build:
            context: '.'
            dockerfile: './dashcore/docker/Dockerfile'
        ports:
            - '9998:9998'
            - '28332:28332'
        volumes:
            - /vdata/dashcore:/data/dashcore

    dashcore-node:
        depends_on:
            - dashcore
        container_name: hs-dashcore-node
        command: /app/dashcore-node/bin/dashcore-node start
        build:
            context: '.'
            dockerfile: './dashcore-node/docker/Dockerfile'
        ports:
            - '3001:3001'
